eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-spring:8761/eureka
      #defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true
  instance:
    hostname: eureka-spring

spring:
  application:
    name: image-service

server:
  port: 8084
