eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://eureka-spring:8761/eureka
    instance:
      preferIpAddress: true
  instance:
    hostname: eureka-spring

spring:
  application:
    name: email-service

server:
  port: 8083
