eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true
  instance:
    hostname: localhost

spring:
  application:
    name: email-service

server:
  port: 8083