CREATE TABLE student_init (
  id INTEGER PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  firstName VARCHAR(64) NOT NULL,
  lastName VARCHAR(64) NOT NULL,
  country VARCHAR(64) NOT NULL,
  city VARCHAR(64) NOT NULL);